### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by dallintanner** [Kadesv/LSK-TradingSite#3]
Decide the pages and components we'll use.

**Comment by dallintanner** [comment]
- [ ] decide on colors
- [ ] mock mobile pages
- [ ] mock desktop pages

**Comment by Kadesv** [comment]
- [ ] About Page
- [ ] Account Page
- [ ] Browse Page
- [ ] Favorites Page (possible component)
- [ ] Message Page (possible component)
- [ ] Post Detail Page
- [ ] Sign Page
